## Importing Libraries

In [1]:
# All needed libraries will be added to this cell
import pandas as pd
from IPython.display import display, Markdown

---

## Importing & Reading Data

In [2]:
# Building the importing & reading function
# This function is built to avoid any reptation in the code
def read_data(df: pd.DataFrame, name: str = "Dataset"):

    # Making bold Markdown header for the dataset and adding separator line
    display(Markdown(f"## Dataset Overview: **{name}**"))
    display(Markdown("---"))
    
    # Output the Shape of the DataFrame to tell us the overall size
    display(Markdown(f"**🔹 Shape:** `{df.shape[0]}` rows * `{df.shape[1]}` columns"))
    
    # Output the Column Names to check the available features
    display(Markdown(f"**🔹 Columns Names:** {list(df.columns)}"))
    
    # Create a combined Summary Table for Data Types and Missing Values
    summary_df = pd.DataFrame({
        'Data Type': df.dtypes,
        'Missing Values': df.isna().sum(),
        '% of Missing Values': (df.isna().sum() / len(df) * 100).round(2)
    })
    display(Markdown("**🔹 Data Types & Missing Values:**"))
    display(summary_df)
    
    # Output the start of the data 
    display(Markdown("**🔹 First 5 Rows:**"))
    display(df.head(5))
    
    # Output the end of the data 
    display(Markdown("**🔹 Last 5 Rows:**"))
    display(df.tail(5))
    
    # Basic Statistical Summary
    display(Markdown("**🔹 Basic Statistics (Numerical Columns):**"))
    display(df.describe().round(2))

In [3]:
# Read the data 
df_gdp = pd.read_excel('../data/Monthly_GDP.xlsx')
df_gt = pd.read_csv('../data/google_trends_categories.csv')

In [4]:
# Execute the function on first dataset
read_data(df_gdp, "Monthly GDP")

## Dataset Overview: **Monthly GDP**

---

**🔹 Shape:** `145` rows * `2` columns

**🔹 Columns Names:** ['Date', 'Monthly GDP']

**🔹 Data Types & Missing Values:**

                  Data Type  Missing Values  % of Missing Values
Date         datetime64[us]               0                  0.0
Monthly GDP         float64               0                  0.0

**🔹 First 5 Rows:**

        Date  Monthly GDP
0 2013-07-01   449.570584
1 2013-08-01   448.920708
2 2013-09-01   452.618708
3 2013-10-01   456.842549
4 2013-11-01   456.478571

**🔹 Last 5 Rows:**

          Date  Monthly GDP
140 2025-03-01   693.765650
141 2025-04-01   710.078987
142 2025-05-01   721.935668
143 2025-06-01   724.285345
144 2025-07-01   722.505363

**🔹 Basic Statistics (Numerical Columns):**

                             Date  Monthly GDP
count                         145       145.00
mean   2019-07-02 01:09:31.034482       585.25
min           2013-07-01 00:00:00       438.41
25%           2016-07-01 00:00:00       504.01
50%           2019-07-01 00:00:00       580.95
75%           2022-07-01 00:00:00       660.52
max           2025-07-01 00:00:00       754.23
std                           NaN        89.06

In [5]:
# Execute the function on second dataset
read_data(df_gt, "Google Trends Categories")

## Dataset Overview: **Google Trends Categories**

---

**🔹 Shape:** `146` rows * `17` columns

**🔹 Columns Names:** ['date', 'Arts & Entertainment', 'Autos & Vehicles', 'Beauty & Fitness', 'Books & Literature', 'Business & Industrial', 'Computers & Electronics', 'Finance', 'Food & Drink', 'Health', 'Internet & Telecom', 'Jobs & Education', 'Law & Government', 'People & Society', 'Real Estate', 'Shopping', 'Travel']

**🔹 Data Types & Missing Values:**

                        Data Type  Missing Values  % of Missing Values
date                          str               0                  0.0
Arts & Entertainment        int64               0                  0.0
Autos & Vehicles            int64               0                  0.0
Beauty & Fitness            int64               0                  0.0
Books & Literature          int64               0                  0.0
Business & Industrial       int64               0                  0.0
Computers & Electronics     int64               0                  0.0
Finance                     int64               0                  0.0
Food & Drink                int64               0                  0.0
Health                      int64               0                  0.0
Internet & Telecom          int64               0                  0.0
Jobs & Education            int64               0                  0.0
Law & Government            int64               0                  0.0
People & Society            int64               0                  0.0
Real Estate                 int64               0                  0.0
Shopping                    int64               0                  0.0
Travel                      int64               0                  0.0

**🔹 First 5 Rows:**

,date,Arts & Entertainment,Autos & Vehicles,Beauty & Fitness,Books & Literature,Business & Industrial,Computers & Electronics,Finance,Food & Drink,Health,Internet & Telecom,Jobs & Education,Law & Government,People & Society,Real Estate,Shopping,Travel
0,2013-07,96,92,54,42,40,75,7,52,24,97,55,67,63,28,39,32
1,2013-08,94,93,54,39,35,77,7,41,25,96,33,62,57,33,44,42
2,2013-09,80,90,54,38,39,73,7,41,26,99,37,57,46,37,42,40
3,2013-10,75,83,48,34,37,73,6,37,26,90,21,46,41,33,40,33
4,2013-11,75,84,46,39,38,75,7,41,31,91,22,49,44,35,42,33

**🔹 Last 5 Rows:**

,date,Arts & Entertainment,Autos & Vehicles,Beauty & Fitness,Books & Literature,Business & Industrial,Computers & Electronics,Finance,Food & Drink,Health,Internet & Telecom,Jobs & Education,Law & Government,People & Society,Real Estate,Shopping,Travel
141,2025-04,62,73,86,56,85,80,44,73,91,74,34,73,68,87,90,81
142,2025-05,58,66,87,55,100,86,42,74,91,73,42,82,67,81,94,88
143,2025-06,60,77,91,54,95,82,41,79,89,74,51,82,68,88,100,89
144,2025-07,57,73,89,53,89,87,37,71,88,78,52,76,62,90,90,76
145,2025-08,54,72,82,52,81,84,37,74,82,73,50,71,64,87,85,92

**🔹 Basic Statistics (Numerical Columns):**

,Arts & Entertainment,Autos & Vehicles,Beauty & Fitness,Books & Literature,Business & Industrial,Computers & Electronics,Finance,Food & Drink,Health,Internet & Telecom,Jobs & Education,Law & Government,People & Society,Real Estate,Shopping,Travel
count,146.00,146.00,146.00,146.00,146.00,146.00,146.00,146.00,146.00,146.00,146.00,146.00,146.00,146.00,146.00,146.00
mean,66.23,72.55,64.95,47.22,63.23,66.55,24.55,62.29,60.97,72.23,36.04,62.05,55.40,65.88,67.03,59.34
std,12.88,11.12,15.34,8.22,16.28,10.60,17.08,12.30,22.69,10.50,10.71,10.58,12.79,17.07,16.96,16.55
min,47.00,47.00,45.00,34.00,35.00,46.00,6.00,37.00,24.00,54.00,18.00,42.00,37.00,28.00,39.00,32.00
25%,57.00,64.00,53.00,41.25,49.00,58.25,13.00,52.00,43.00,64.00,27.00,54.00,46.00,52.25,51.25,45.00
50%,61.00,72.50,59.00,45.00,61.00,65.00,19.00,61.00,54.00,72.00,34.50,60.00,52.00,68.00,65.00,58.50
75%,77.00,81.00,79.75,51.75,77.75,75.75,37.00,73.75,84.75,77.00,43.75,70.00,64.75,80.00,82.75,70.75
max,97.00,100.00,100.00,100.00,100.00,90.00,100.00,100.00,100.00,100.00,69.00,85.00,100.00,100.00,100.00,100.00

---